<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title-block')</title>
    <link rel="stylesheet" href="/css/app.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<body>
    <div class="header">
        @include('inc.header')
    </div>

    

    <div class="container">

        @include('inc.messages')

        <div class="row">
          
            @if(Request::is('/','about','contact'))
                <div class="col-8"> 
                    @yield('content')
                </div>
                <div class="col-4">    
                    @include('inc.aside')
                </div>
            @else
                @yield('content')
            @endif

        </div>



        @if(Request::is('about'))
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
        @endif
        @if(Request::is('/'))
            @include('inc.hero')
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>  
        @endif
        @if(Request::is('contact'))
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore asperiores assumenda natus ea impedit? Natus eos maxime magni harum recusandae aliquam veritatis nesciunt provident! Ipsam cupiditate sequi accusantium id officiis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum voluptatum ipsa placeat quia eveniet, velit in dignissimos saepe, assumenda incidunt vitae porro temporibus aliquam officia. Libero dignissimos doloribus amet porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum ratione quis sit optio, ipsa numquam magni facilis quod illum quas! Nihil ratione fugiat similique! Obcaecati dignissimos at esse rem perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque dignissimos, voluptatibus voluptatum itaque adipisci eius deleniti placeat aut inventore voluptate saepe assumenda eveniet recusandae quo sapiente cum id aliquid at. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum accusantium minus labore expedita quos error enim beatae aperiam consequatur temporibus, mollitia autem dolorem officia aliquam veritatis maiores incidunt cupiditate velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati neque hic qui voluptatibus accusantium aspernatur excepturi quo officiis minima soluta, temporibus eius sint accusamus quibusdam unde, nemo ipsam autem reiciendis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, est vero iusto non possimus, expedita vitae, ipsa natus illo mollitia quasi tempore libero sapiente magnam ad. Ipsam nemo alias aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt velit voluptates asperiores, repellendus dicta dolores! Provident quos excepturi consequuntur, veritatis, vel sint, dolorum illo fugiat sequi odio quas ad!</p>
        @endif
 
   
    </div>
    
    <div class="footer">
        @include('inc.footer')
    </div>

        

</body>
</html>